### ISSUE TITLE
A code problem

### ISSUE THREAD

**Issue by lsj1111** [canoe-Z/PETDet#10]
there is a code:from . import convex_ext in mmrotate/ops/convex/convex_wrapper.py ,but here is not have a diretory named convex_ext ,so i want to know how to solve this problem,
The message of problem is this:
ImportError: cannot import name 'convex_ext' from partially initialized module 'mmrotate.ops.convex'

**Comment by canoe-Z** [comment]
It seems that the issue is caused by the lack of compiled operators for calculating rotated GIoU. Please carefully check whether you have followed the complete installation steps.
