### ISSUE TITLE
This model is suitable for shelf product detection? 

### ISSUE THREAD

**Issue by skipper-zc** [canoe-Z/PETDet#2]
May I ask if this model is suitable for shelf product detection? They are all fine-grained object detection tasks. And does it support Coco format data？

**Comment by canoe-Z** [comment]
Not planned.

**Comment by canoe-Z** [comment]
Not planned.

**Comment by canoe-Z** [comment]
We have not yet tried using PETDet for the shelf product detection task. However, we believe that the improvements proposed in PETDet could be beneficial for this task.
