### ISSUE TITLE
the num_classes in QualityOrientedRPNHead

### ISSUE THREAD

**Issue by sqdcbbj** [canoe-Z/PETDet#3]
Hello, I would like to know if the num_class in QualityOrientedRPNHead is fixed to 1, and RPN only distinguishes foreground and background, right? Thank you

**Comment by canoe-Z** [comment]
Yes, you're correct. The QualityOrientedRPNHead serves as an enhanced RPN, designed to deliver better results in distinguishing foreground and background.

**Comment by sqdcbbj** [comment]
Hello, there are many negative values in the centerness_targets I obtained while using QOPN, resulting in a loss of Nan. May I ask what may be the reason for this?

**Comment by canoe-Z** [comment]
Please ensure that the assigner in RPN is the `RotatedATSSAssigner` implemented in this repo, not the `ATSSObbAssigner`. We have observed that using `ATSSObbAssigner` may cause negative values in `centerness_targets`.
