### ISSUE TITLE
该模型在ShipRSImageNet数据集上的L0任务的mAP50精度是多少？

### ISSUE THREAD

**Issue by guoxxxxxxx** [canoe-Z/PETDet#4]
您好作者，我想请问一下，该模型在ShipRSImageNet数据集上的L0任务上的的mAP50精度是多少？方便的话可以告诉我一下吗？

**Comment by guoxxxxxxx** [comment]
我看在论文中，您做的是L3任务的实验。

**Comment by canoe-Z** [comment]
We have not yet conducted experiments for the L0 task on ShipRSImageNet, looking forward to your attempt for more expermental results of PETDet with different settings.
