### ISSUE TITLE
A bug in Model forward

### ISSUE THREAD

**Issue by chujun200** [canoe-Z/PETDet#7]
![287377471](https://github.com/user-attachments/assets/b492565e-b0d3-4633-baf5-e88d432ca08a)

I noticed an issue in the BCFN （CIM）forward function. Currently, the torch.chunk operation is applied twice to x1, instead of once each to x1 and x2. As a result, x2 is being ignored in the chunking process, which means the model is not properly using the data from x2.

**Comment by canoe-Z** [comment]
Thank you for your interest in PETDet. We have confirmed that the bug you reported in BCFN does exist. We will fix the bug as soon as possible and upload new models.

**Comment by canoe-Z** [comment]
Thank you for raising the issue. We have fixed this bug and released new models.
