### ISSUE TITLE
horizontal box detection

### ISSUE THREAD

**Issue by sqdcbbj** [canoe-Z/PETDet#9]
Can PETDET be used for horizontal box detection？

**Comment by canoe-Z** [comment]
Yes, although experiments of PETDet were conducted on rotated object detection, there aren't many designs in PETDet specifically for rotated boxes. For ```QOPN```, you can simply remove the angle prediction and calculate horizontal IoU loss to predict horizontal proposals. The ```BCFN``` and ```ARL``` module can be used directly without modification. Following this approach, we have designed ```PETDet-H``` for horizontal box detection and conducted some experiments, but we currently have no plans to release these code. We recommend that you modify PETDet yourself for further research.
